---
# Create Authentication file for access to postgres database
- name: Create pgpass file
  template:
    src: .pgpass.j2
    dest: ~/.pgpass
    owner: root
    group: root
    mode: 0600

# Create config file that will define the DB Engine
- name: Create kamctlrc Config
  template:
    src: kamctlrc.j2
    dest: /usr/local/etc/kamailio/kamctlrc
    owner: root
    group: root
    mode: 0644

# Run kamdbctl to setup kamailio database
- name: Create Database
  shell: "/usr/local/sbin/kamdbctl create {{ kam_dbname }}"
  run_once: true
  ignore_errors: true     #  I need to look at this

#Create default config file
- name: Create Kamailo Config
  template:
    src: kamailio.cfg.j2
    dest: "/usr/local/etc/kamailio/kamailio.cfg"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart kamailio

# Create SystemD Service
- name: Create Kamailio SystemD Service
  template:
    src: kamailio.service.j2
    dest: /etc/systemd/system/kamailio.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart kamailio