---
- name: Create Kamailio Database.
  postgresql_db:
    name: "{{ db_kam }}"
    state: present
    login_user: "{{ dbuser_root }}"
  environment:
    PGHOST: "{{ dbhost }}"
    PGPORT: "{{ dbport }}"
    PGPASSWORD: "{{ dbpass_root }}"
    PGDATABASE: "{{ db_root }}"
  run_once: true
  register: _kamailio_database

- name: Create Tables in Kamailio Database
  shell:
    cmd: |
      cat {{ kamailio_dest_directory }}/kamailio/utils/kamctl/postgres/version-create.sql > /tmp/db_import.sql
      cat {{ kamailio_dest_directory }}/kamailio/utils/kamctl/postgres/*.sql > /tmp/db_import.sql
      psql postgres://{{ dbuser_kam }}:{{ dbpass_kam }}@{{ dbhost }}:{{ dbport }}/{{ db_kam }} -f /tmp/db_import.sql
  environment:
    PGHOST: "{{ dbhost }}"
    PGPORT: "{{ dbport }}"
    PGUSER: "{{ dbuser_kam }}"
    PGPASSWORD: "{{ dbpass_kam }}"
    PGDATABASE: "{{ db_kam }}"
  when: _kamailio_database.changed
  run_once: true

- name: Create Kamailio user.
  postgresql_user:
    name: "{{ dbuser_kam }}"
    password: "{{ dbpass_kam }}"
    login_user: "{{ dbuser_root }}"
  environment:
    PGHOST: "{{ dbhost }}"
    PGPORT: "{{ dbport }}"
    PGPASSWORD: "{{ dbpass_root }}"
    PGDATABASE: "{{ db_root }}"
  run_once: true

- name: Grant all privledges to user:{{ dbuser_kam }} on database:{{ db_kam }}.
  postgresql_privs:
    db: "{{ db_kam }}"
    privs: ALL
    type: database
    role: "{{ dbuser_kam }}"
    login_user: "{{ dbuser_root }}"
  environment:
    PGHOST: "{{ dbhost }}"
    PGPORT: "{{ dbport }}"
    PGPASSWORD: "{{ dbpass_root }}"
    PGDATABASE: "{{ db_root }}"
  run_once: true

- name: Add Recorders as dispatcher destinations.
  command: |
    psql -c "INSERT INTO dispatcher
    VALUES ('{{ index }}', '{{ disp_set }}', 'sip:{{ item.ip }}:{{ item.port }};transport={{ item.protocol }}', '{{ item.flags| default(0) }}', '{{ item.priority | default(0) }}', '{{ item.attrs | default('') }}', '{{ item.name }}')
    ON CONFLICT (id)
    DO UPDATE SET
    id={{ index }}, setid={{ disp_set }}, destination='sip:{{ item.ip }}:{{ item.port }};transport={{ item.protocol }}', flags={{ item.flags| default(0) }}, priority={{ item.priority | default(0) }}, attrs='{{ item.attrs | default=('') }}'', description='{{ item.name }}';"
  run_once: true
  loop: "{{ disptacher_destinations }}"
  loop_control:
    index_var: index
  environment:
    PGHOST: "{{ dbhost }}"
    PGPORT: "{{ dbport }}"
    PGUSER: "{{ dbuser_kam }}"
    PGPASSWORD: "{{ dbpass_kam }}"
    PGDATABASE: "{{ db_kam }}"
  when: dispatcher_destination.changed

