---
# Create User and Group
- name: Create Kamailio group
  group:
    name: kamailio
    state: present

- name: Create Kamailio user
  user:
    name: kamailio
    system: true
    shell: "/usr/sbin/nologin"
    group: kamailio
    move_home: yes
    home: /var/run/kamailio

# GIT source code
- name: Create directory for source code
  file:
    path: "{{ kamailio_dest_directory }}"
    state: directory
    mode: 0755

- name: Git clone Kamailio
  git:
    repo: git://git.kamailio.org/kamailio
    dest: "{{ kamailio_dest_directory }}/kamailio"
    recursive: no
    clone: yes
    version: origin/{{ kamailio_version }}

# Compile Build Files
- name: Compile Build Files
  shell: "{{ item }}"
  with_items:
    - "cd {{ kamailio_dest_directory }}/kamailio && make include_modules='db_postgres' cfg"
    - "cd {{ kamailio_dest_directory }}/kamailio && make all"
    - "cd {{ kamailio_dest_directory }}/kamailio && make install"






