---
# Create User and Group
- name: Create Kamailio group
  group:
    name: kamailio
    state: present
    system: true

- name: Create the Kamailio user.
  user:
    name: kamailio
    groups: kamailio
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

# GIT source code
- name: Create directory for Kamailio source code.
  file:
    path: "{{ kamailio_dest_directory }}"
    state: directory
    mode: 0755

- name: Git clone Kamailio repo.
  git:
    repo: git://git.kamailio.org/kamailio
    dest: "{{ kamailio_dest_directory }}/kamailio"
    recursive: no
    clone: yes
    version: origin/{{ kamailio_version }}

# Compile Build Files
- name: Compile Build Files - Kamailio
  shell: "{{ item }}"
  with_items:
    - "cd {{ kamailio_dest_directory }}/kamailio && make include_modules='db_postgres' cfg"
    - "cd {{ kamailio_dest_directory }}/kamailio && make all"
    - "cd {{ kamailio_dest_directory }}/kamailio && make install"
  notify:
    - restart kamailio

# # Create config file that will define the DB Engine
# - name: Create kamctlrc Config
#   template:
#     src: kamctlrc.j2
#     dest: /usr/local/etc/kamailio/kamctlrc
#     owner: root
#     group: root
#     mode: 0644

# # Create Authentication file for access to postgres database
# - name: Create .pgpass file
#   template:
#     src: .pgpass.j2
#     dest: ~/.pgpass
#     owner: root
#     group: root
#     mode: 0600

# # Run kamdbctl to setup kamailio database
# - name: Create Kamailio database.
#   become: true
#   shell: "/usr/local/sbin/kamdbctl create {{ db_kam }}"
#   run_once: true




