---
# Create User and Group
- name: Create Kamailio group.
  group:
    name: kamailio
    state: present
    system: true

- name: Create Kamailio user.
  user:
    name: kamailio
    groups: kamailio
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

# GIT source code
- name: Create directory for Kamailio source code.
  file:
    path: "{{ kamailio_dest_directory }}"
    state: directory
    mode: 0755

- name: Clone Kamailio repository.
  git:
    repo: https://github.com/kamailio/kamailio.git
    dest: "{{ kamailio_dest_directory }}/kamailio"
    recursive: false
    clone: true
    version: "{{ kamailio_version }}"




# Compile Build Files

- name: Compile Kamailio build files with MySQL.
  shell: "{{ item }}"
  with_items:
    - "cd {{ kamailio_dest_directory }}/kamailio && make include_modules='db_mysql' cfg"
    - "cd {{ kamailio_dest_directory }}/kamailio && make all"
    - "cd {{ kamailio_dest_directory }}/kamailio && make install"
  notify:
    - restart kamailio
  when: not db_postgresql


- name: Compile Kamailio build files with PostgreSQL.
  shell: "{{ item }}"
  with_items:
    - "cd {{ kamailio_dest_directory }}/kamailio && make include_modules='db_postgres' cfg"
    - "cd {{ kamailio_dest_directory }}/kamailio && make all"
    - "cd {{ kamailio_dest_directory }}/kamailio && make install"
  notify:
    - restart kamailio
  when: db_postgresql

# - name: Compile Kamailio build files.
#   shell: "{{ item }}"
#   with_items:
#     - "cd {{ kamailio_dest_directory }}/kamailio && make include_modules='{% if db_postgresql == true %}db_postgres{% else %}db_mysql{% endif %}' cfg"
#     - "cd {{ kamailio_dest_directory }}/kamailio && make all"
#     - "cd {{ kamailio_dest_directory }}/kamailio && make install"
#   notify:
#     - restart kamailio
#   # when: db_postgresql