---
# Create User and Group
- name: Create rtpproxy group
  group:
    name: rtpproxy
    state: present

- name: Create rtpproxy user
  user:
    name: rtpproxy
    system: true
    shell: "/usr/sbin/nologin"
    group: rtpproxy
    move_home: yes
    home: /var/run/rtpproxy


# Create Directory and Clone Repo
- name: Create directory for source code from Git
  file:
    path: "{{ rtpproxy_dest_directory }}"
    state: directory
    mode: 0755

- name: Git clone Kamailio
  git:
    repo: https://github.com/sippy/rtpproxy.git
    dest: "{{ rtpproxy_dest_directory }}/rtpproxy"
    recursive: yes
    clone: yes

# Compile Files
- name: Compile Build Files
  shell: "{{ item }}"
  with_items:
    - "cd {{ rtpproxy_dest_directory }}/rtpproxy && ./configure"
    - "cd {{ rtpproxy_dest_directory }}/rtpproxy && make all"
    - "cd {{ rtpproxy_dest_directory }}/rtpproxy && make install"



