---
# Create User and Group
- name: Create Rtpproxy group.
  group:
    name: rtpproxy
    state: present
    system: true

- name: Create the Rtpproxy user.
  user:
    name: rtpproxy
    groups: rtpproxy
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

# Create Directory and Clone Repo
- name: Create directory for source code from Git
  file:
    path: "{{ rtpproxy_dest_directory }}"
    state: directory
    mode: 0755

- name: Git clone Kamailio
  git:
    repo: https://github.com/sippy/rtpproxy.git
    dest: "{{ rtpproxy_dest_directory }}/rtpproxy"
    recursive: yes
    clone: yes

# Compile Files
- name: Compile Build Files
  shell: "{{ item }}"
  with_items:
    - "cd {{ rtpproxy_dest_directory }}/rtpproxy && ./configure"
    - "cd {{ rtpproxy_dest_directory }}/rtpproxy && make all"
    - "cd {{ rtpproxy_dest_directory }}/rtpproxy && make install"
  notify:
    - restart rtpproxy



