---
# tasks file for sip-proxy

# Install Dependencies
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - kamailio
    - rtpproxy

- name: Install dependencies (RedHat).
  include: prep-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - kamailio
    - rtpproxy
    - database

- name: Install dependencies (Debian).
  include: prep-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - kamailio
    - rtpproxy
    - database

# Check for previously installed Kamailio and Rtpproxy
- name: Check for existing Kamailio binary.
  stat:
    path: "{{ kamailio_bin }}"
  register: _kamailio_install
  tags: kamailio

- name: Check Kamailio version.
  command: "{{ kamailio_bin }} --version"
  register: _kamailio_version
  when: "_kamailio_install.stat.exists"
  changed_when: False
  failed_when: False
  tags: kamailio

- name: Check for existing Rtpproxy binary.
  stat:
    path: "{{ rtpproxy_bin }}"
  register: _rtpproxy_install
  tags: rtpproxy

# Check Database Configuration
- name: Check if Database {{ db_kam }} exists.
  command: "psql -c \"\\list\" | grep {{ db_kam }}"
  environment:
    PGHOST: "{{ dbhost }}"
    PGPORT: "{{ dbport }}"
    PGUSER: "{{ dbuser_root }}"
    PGPASSWORD: "{{ dbpass_root }}"
    PGDATABASE: "{{ db_root }}"
  register: _db_kam

- name: Check if user {{ dbuser_kam }} exists.
  command: "psql -c \"\\du\" | grep {{ dbuser_kam }}"
  when: "_db_kam.stat.exists"
  environment:
    PGHOST: "{{ dbhost }}"
    PGPORT: "{{ dbport }}"
    PGUSER: "{{ dbuser_root }}"
    PGPASSWORD: "{{ dbpass_root }}"
    PGDATABASE: "{{ db_root }}"
  register: _dbuser_kam

- name: Check if dispatcher table exists.
  command: "psql -c \"\\dt\" | grep dispatcher"
  when: _db_kam.stat.exists and _dbuser_kam.stat.exists
  environment:
    PGHOST: "{{ dbhost }}"
    PGPORT: "{{ dbport }}"
    PGUSER: "{{ dbuser_kam }}"
    PGPASSWORD: "{{ dbpass_kam }}"
    PGDATABASE: "{{ db_kam }}"
  register: _dbtable_kam

# Install Kamailio and Rtpproxy
- name: Install Rtpproxy.
  include: install_rtpproxy.yml
  when: "not _rtpproxy_install.stat.exists"
  tags:
    - rtpproxy

- name: Install Kamailio.
  include: install_kamailio.yml
  when: "not _kamailio_install.stat.exists or kamailio_version is not defined or kamailio_version|string not in _kamailio_version.stdout"
  tags:
    - kamailio

# Configure Kamailio Database
- name: Configure Kamailio database.
  include: configure_database.yml
  when: "not _db_kam.stat.exists or not _dbuser_kam.stat.exists or not _dbtable_kam.stat.exists"
  tags:
    - kamailio
    - database

# Generate Configuration files
- name: Configure Rtpproxy.
  include: configure_rtpproxy.yml
  tags:
    - rtpproxy

- name: Configure Kamailio.
  include: configure_kamailio.yml
  tags:
    - kamailio

- name: Create Dispatcher SQL script.
  template:
    src: dispatcher-list.sql.j2
    dest: "/usr/local/etc/kamailio/dispatcher.list.sql"
    owner: root
    group: root
    mode: 0644
  register: _dispatcher_destinations

- name: Update dispatcher table.
  postgresql_query:
    db: "{{ db_kam }}"
    login_host: "{{ dbhost }}"
    port: "{{ dbport }}"
    login_user: "{{ dbuser_kam }}"
    login_password: "{{ dbpass_kam }}"
    path_to_script: "/usr/local/etc/kamailio/dispatcher.list.sql"
  when: _dispatcher_destinations.changed
  run_once: true
  notify:
   - reload dispatcher
