---
# tasks file for proxy

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - kamailio
    - rtpproxy

# Install Dependencies
- name: Install Dependencies (RedHat).
  include: prep-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - kamailio
    - rtpproxy
    - database

- name: Install Dependencies (Debian).
  include: prep-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - kamailio
    - rtpproxy
    - database


# Check for previously installed Kamailio
- name: Check for existing Kamilio binary.
  stat:
    path: "{{ kamailio_bin }}"
  register: _kamailio_install
  tags: kamailio

- name: Check Kamailio version if binary exists.
  command: "{{ kamailio_bin }} --version"
  register: _kamailio_version
  when: "_kamailio_install.stat.exists"
  changed_when: False
  failed_when: False
  tags: kamailio

# Check for previously installed rtpproxy
- name: Check for existing rtpproxy binary.
  stat:
    path: "{{ rtpproxy_bin }}"
  register: _rtpproxy_install
  tags: rtpproxy

# Check if Database is present
- name: Check is database is present
  shell:
    cmd: psql postgres://{{ dbrootuser }}:{{ dbrootpass }}@{{ dbhost }}:{{dbport}}/{{ dbrootname }} -c '\list' | grep {{ kam_dbname }}
  register: _db_status
  failed_when: _db_status.rc == 2
  changed_when: False
  run_once: true
  tags:
   - kamailio
   - database

- name: Configure Databaes
  include: configure_databse.yml
  when: "kam_dbname not in _db_status.stdout"
  tags:
    - kamailio
    - database

# Downaload source code and complie
- name: Install Kamailio.
  include: install_kamailio.yml
  when: "not _kamailio_install.stat.exists or kamailio_version is not defined or kamailio_version|string not in _kamailio_version.stdout"
  tags:
    - kamailio

- name: Install rtpproxy.
  include: install_rtpproxy.yml
  when: "not _rtpproxy_install.stat.exists"
  tags:
    - rtpproxy

# Generate Configuration files
- name: Configure Kamailio.
  include: configure_kamailio.yml
  tags:
    - kamailio

- name: Configure rtpproxy.
  include: configure_rtpproxy.yml
  tags:
    - rtpproxy