---
# Install dependencies
- name: Debian - Install Package Dependencies
  become: true
  apt:
    update_cache: true
    state: present
    pkg: "{{ debian_dependencies }}"
  notify:
    - restart kamailio
    - restart rtpproxy

- name: Install psycopg2 for ansible to be able to create postgresql.
  become: yes
  pip:
    name: psycopg2-binary
  when: ansible_os_family == "Debian"


