---
# Install dependencies
- name: Install Package Dependencies (Debian).
  become: true
  apt:
    update_cache: true
    state: present
    pkg: "{{ debian_dependencies }}"
  notify:
    - restart kamailio
    - restart rtpproxy


# Install mysql if needed
- name: Install MySQL
  become: true
  apt:
    update_cache: true
    state: present
    pkg: default-mysql-server
  when: db_postgresql