---
# Install dependencies
- name: Install Package Dependencies - Debian
  become: true
  apt:
    update_cache: true
    state: present
    pkg: "{{ debian_dependencies }}"
  notify:
    - restart kamailio
    - restart rtpproxy

# - name: Install psycopg2 for ansible to be able to create postgresql.
#   become: true
#   pip:
#     name: psycopg2-binary
#   when: ansible_os_family == "Debian"
