---
# Install dependencies
- name: Debian - Install Package Dependencies
  become: true
  apt:
    update_cache: true
    state: present
    pkg: "{{ debian_dependencies }}"
  notify:
    - restart kamailio
    - restart rtpproxy



