---
# handlers file for proxy
- name: restart kamailio
  become: true
  systemd:
    daemon_reload: true
    name: kamailio
    state: restarted

- name: restart rtpproxy
  become: true
  systemd:
    daemon_reload: true
    name: rtpproxy
    state: restarted

- name: Reload dispatcher module
  become: true
  shell: "kamctl dispatcher reload"
