---
- name: Converge
  hosts: all
  become: true
  vars_files:
   - vars/sipproxy.yml
  pre_tasks:
   - name: Install Test Depedencies.
     become: true
     apt:
      update_cache: true
      name: "{{ item }}"
      state: present
     with_items:
      - postgresql
      - python3-pip

   - name: Install psycopg2 for ansible to be able to create postgresql users
     become: true
     pip: name=psycopg2-binary
     when: ansible_os_family == "Debian"

   - name: Start Postgres Service
     service:
      name: postgresql
      state: started

   - name: Create Root Database.
     become_user: postgres
     postgresql_db:
      name: "{{ db_root }}"
      state: present

   - name: Create User Database user.
     become_user: postgres
     postgresql_user:
      name: "{{ dbuser_root }}"
      password: "{{ dbpass_root }}"
      role_attr_flags: "SUPERUSER"

  roles:
   - role: ansible-role-sip-proxy
